version: "3.9"
networks:
  bookommender:
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - PORT=$FRONTEND_PORT
    image: bookommender-f:latest
    volumes:
      - ./frontend/:/app/src
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    networks:
      - bookommender
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - PORT=$BACKEND_PORT
    image: bookommender-b:latest
    environment:
      - "ES_URL=http://root:root@elasticsearch:${ELASTICSEARCH_PORT}"
    volumes:
      - ./backend:/app/src
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      - bookommender
    depends_on:
      - kibana

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - bookommender
    ports:
      - "${ELASTICSEARCH_PORT}:${ELASTICSEARCH_PORT}"
    volumes:
      - ./backend/esdata:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:8.5.3
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:$ELASTICSEARCH_PORT
    networks:
      - bookommender
    depends_on:
      - elasticsearch
    ports:
      - "${KIBANA_PORT}:${KIBANA_PORT}"
