export const authors = [
  'Agatha Christie',
  'Aimee Thurlo',
  'Alan Dean Foster',
  'Albert Camus',
  'Alfred Hitchcock',
  'Alice Walker',
  'Alistair Maclean',
  'Anais Nin',
  'Andre Norton',
  'Andrea Camilleri',
  'Andrew M. Greeley',
  'Ann M. Martin',
  'Anne Mather',
  'Anne Mcallister',
  'Anne Mccaffrey',
  'Anne Perry',
  'Anne Rice',
  'Anne Stuart',
  'Annette Broadrick',
  'Anthony Trollope',
  'Arlene James',
  'Arnette Lamb',
  'Arthur C. Clarke',
  'Arthur Conan Doyle',
  'Arthur Conan, Sir Doyle',
  'Arthur Upfield',
  'Astrid Lindgren',
  'Author Unknown',
  'Avi',
  'Barbara Boswell',
  'Barbara Bretton',
  'Barbara Cartland',
  'Barbara Delinsky',
  'Barbara Hambly',
  'Barbara Michaels',
  'Barbara Park',
  'Barbara Wood',
  'Beatrix Potter',
  'Ben Bova',
  'Ben M. Baglio',
  'Bernard Cornwell',
  'Bertrice Small',
  'Bethany Campbell',
  'Betsy Byars',
  'Betsy Haynes',
  'Better Homes And Gardens',
  'Betty Crocker',
  'Betty Neels',
  'Beverly Cleary',
  'Bill Pronzini',
  'Bodie Thoene',
  'Bonnie Bryant',
  'Bruce Coville',
  'C. J. Cherryh',
  'C. S. Lewis',
  'C.J. Cherryh',
  'Cait London',
  'Carla Cassidy',
  'Carol Finch',
  'Carole Mortimer',
  'Carole Nelson Douglas',
  'Caroline B. Cooney',
  'Carolyn Keene',
  'Cassie Edwards',
  'Catherine Cookson',
  'Catherine Coulter',
  'Catherine George',
  'Cathy Gillen Thacker',
  'Cathy Guisewite',
  'Charles Bukowski',
  'Charles De Lint',
  'Charles Dickens',
  'Charles M. Schulz',
  'Charles R. Swindoll',
  'Charles Sheffield',
  'Charlotte Lamb',
  'Charlotte Macleod',
  'Chelsea Quinn Yarbro',
  'Cherie Bennett',
  'Christian Jacq',
  'Christine Rimmer',
  'Christopher Golden',
  'Christopher Pike',
  'Christopher Stasheff',
  'Clamp',
  'Clive Cussler',
  'Connie Mason',
  'Constance Obanyon',
  'Dallas Schulze',
  'Dana Fuller Ross',
  'Dana Stabenow',
  'Danielle Steel',
  'Dav Pilkey',
  'Dave Duncan',
  'David A. Adler',
  'David Drake',
  'David Eddings',
  'David Lodge',
  'David P. Jordan',
  'David Weber',
  'Dean Koontz',
  'Dean R. Koontz',
  'Dean Wesley Smith',
  'Debbie Dadey',
  'Debbie Macomber',
  'Deepak Chopra',
  'Diana G. Gallagher',
  'Diana Palmer',
  'Diana Wynne Jones',
  'Diane Carey',
  'Diane Duane',
  'Diane Hoh',
  'Dick Francis',
  'Dick King-Smith',
  'Dick Stivers',
  'Disney Enterprises Inc',
  'Dixie Browning',
  'Don Coldsmith',
  'Don Pendleton',
  'Donald E. Westlake',
  'Donald J. Sobol',
  'Doris Lessing',
  'Doris May Lessing',
  'Dorling Kindersley Publishing',
  'Dorothy Garlock',
  'Douglas Adams',
  'Ed Mcbain',
  'Edgar Allan Poe',
  'Edward Packard',
  'Elaine Barbieri',
  'Elizabeth Bevarly',
  'Elizabeth George',
  'Elizabeth Levy',
  'Elizabeth Lowell',
  'Elizabeth Peters',
  'Ellen Small',
  'Ellis Peters',
  'Elmore Leonard',
  'Emile Zola',
  'Emilie Richards',
  'Emily Chase',
  'Emma Darcy',
  'Emma Goldrick',
  'Enid Blyton',
  'Erle Stanley Gardner',
  'Erma Bombeck',
  'Ernest Hemingway',
  'Esther Friesner',
  'Eve Bunting',
  'F. Paul Wilson',
  'F. Scott Fitzgerald',
  'Fay Weldon',
  'Faye Kellerman',
  'Fern Michaels',
  'Fodors',
  'Francine Pascal',
  'Franklin W. Dixon',
  'Franz Kafka',
  'Fred Saberhagen',
  'Frederik Pohl',
  'Fyodor Dostoyevsky',
  'Gabriel Garcia Marquez',
  'Gail Herman',
  'Gardner Dozois',
  'Gary Paulsen',
  'Gene Wolfe',
  'George Macdonald',
  'Georges Simenon',
  'Georgette Heyer',
  'Gerald Durrell',
  'Gertrude Chandler Warner',
  'Gilbert Morris',
  'Gina Wilkins',
  'Golden Books',
  'Gordon Korman',
  'Gordon R. Dickson',
  'Grace Livingston Hill',
  'Graham Greene',
  'Graham Masterton',
  'Greg Bear',
  'Gregory Benford',
  'H. G. Wells',
  'Harlan Ellison',
  'Harold Robbins',
  'Harriet Ziefert',
  'Harry Harrison',
  'Harry Turtledove',
  'Heather Graham',
  'Helen Exley',
  'Helene Siegel',
  'Henning Mankell',
  'Henry James',
  'Herge',
  'Hermann Hesse',
  'Honor Books',
  'Ian Rankin',
  'Iris Johansen',
  'Isaac Asimov',
  'Isaac Bashevis Singer',
  'Isabel Allende',
  'Italo Calvino',
  'J. K. Rowling',
  'J. R. R. Tolkien',
  'J.R.R. Tolkien',
  'Jack Canfield',
  'Jack Higgins',
  'Jack Kerouac',
  'Jack L. Chalker',
  'Jack London',
  'Jackie Merritt',
  'Jake Logan',
  'James A. Michener',
  'James Axler',
  'James Howe',
  'James Patterson',
  'Jamie Suzanne',
  'Jane Austen',
  'Jane Belk Moncure',
  'Jane Yolen',
  'Janelle Taylor',
  'Janet Dailey',
  'Janet Evanovich',
  'Janet Quin-Harkin',
  'Janet Woods',
  'Janette Oke',
  'Janice Kaiser',
  'Jasmine Cresswell',
  'Jayne Ann Krentz',
  'Jean Marzollo',
  'Jean Plaidy',
  'Jeanne Betancourt',
  'Jeffrey Archer',
  'Jennifer Blake',
  'Jennifer Greene',
  'Jerry B. Jenkins',
  'Jessica Steele',
  'Jill Shalvis',
  'Jim Davis',
  'Jim Wilson',
  'Joan Aiken',
  'Joan Hess',
  'Joan Hohl',
  'Joan Johnston',
  'Joan Lowery Nixon',
  'Joan Smith',
  'Joanna Cole',
  'Johann Wolfgang Von Goethe',
  'Johanna Lindsey',
  'John D. Macdonald',
  'John Gardner',
  'John Gray',
  'John Grisham',
  'John Irving',
  'John Le Carre',
  'John Peel',
  'John Saul',
  'John Steinbeck',
  'John Updike',
  'Jonathan Kellerman',
  'Jorge Luis Borges',
  'Jose Saramago',
  'Joseph Conrad',
  'Joyce Carol Oates',
  'Jude Deveraux',
  'Judy Blume',
  'Judy Christenberry',
  'Jules Verne',
  'Justine Korman',
  'K. A. Applegate',
  'Karen Robards',
  'Kasey Michaels',
  'Kate Wilhelm',
  'Kate William',
  'Katherine Applegate',
  'Katherine Kurtz',
  'Kathleen Eagle',
  'Kay Hooper',
  'Kelli M. Gary',
  'Ken Follett',
  'Kevin J. Anderson',
  'Kinky Friedman',
  'L. E. Modesitt Jr.',
  'L. Frank Baum',
  'L. Ron Hubbard',
  'Landoll',
  'Larry Mcmurtry',
  'Larry Niven',
  'Laurie Paige',
  'Lawrence Block',
  'Lawrence Sanders',
  'Leigh Greenwood',
  'Lemony Snicket',
  'Len Deighton',
  'Lilian Jackson Braun',
  'Linda Howard',
  'Linda Lael Miller',
  'Lindsay Armstrong',
  'Lindsay Mckenna',
  'Lisa Jackson',
  'Lois Gladys Leppard',
  'Lois Lowry',
  'Loren D. Estleman',
  'Lori Copeland',
  'Lori Foster',
  'Louis Lamour',
  'Louisa May Alcott',
  'Lucy Gordon',
  'Lurlene Mcdaniel',
  'Lydia Adamson',
  'Lynn Erickson',
  'Lynne Graham',
  'M. C. Beaton',
  'Madeleine Lengle',
  'Madeline Baker',
  'Maeve Binchy',
  'Maggie Shayne',
  'Marc Brown',
  'Marcia Muller',
  'Margaret Atwood',
  'Margaret Way',
  'Margaret Weis',
  'Margery Allingham',
  'Marguerite Duras',
  'Marie Ferrarella',
  'Marilyn Kaye',
  'Marilyn Pappano',
  'Mario Vargas Llosa',
  'Marion Chesney',
  'Marion Zimmer Bradley',
  'Mark Stevens',
  'Mark Twain',
  'Martha Grimes',
  'Martin H. Greenberg',
  'Mary Balogh',
  'Mary Daheim',
  'Mary Engelbreit',
  'Mary Higgins Clark',
  'Mary Lynn Baxter',
  'Mary Pope Osborne',
  'Mary-Kate Amp; Ashley Olsen',
  'Matt Christopher',
  'Max Allan Collins',
  'Max Brand',
  'Max Lucado',
  'Mel Odom',
  'Mercedes Lackey',
  'Mercer Mayer',
  'Merline Lovelace',
  'Michael A. Stackpole',
  'Michael Jan Friedman',
  'Michael Moorcock',
  'Michael Phillips',
  'Michael Teitelbaum',
  'Michaela Muntean',
  'Mike Resnick',
  'Milan Kundera',
  'Miranda Lee',
  'Mouse Works',
  'Muriel Jensen',
  'Naoko Takeuchi',
  'Nathaniel Hawthorne',
  'Neil Gaiman',
  'Ngaio Marsh',
  'Nora Roberts',
  'Norman Bridwell',
  'Not Applicable (Na )',
  'Orson Scott Card',
  'Oscar Wilde',
  'Outlet',
  'P. D. James',
  'P. G. Wodehouse',
  'P.G. Wodehouse',
  'Pablo Neruda',
  'Patricia Cornwell',
  'Patricia Highsmith',
  'Patricia Reilly Giff',
  'Patricia Rosemoor',
  'Patricia Wentworth',
  'Patrick Obrian',
  'Paul Auster',
  'Paul Theroux',
  'Paul Zindel',
  'Paulette Bourgeois',
  'Paulo Coelho',
  'Pearl S. Buck',
  'Penny Jordan',
  'Peter David',
  'Philip Jose Farmer',
  'Philip K. Dick',
  'Philip Roth',
  'Phyllis A. Whitney',
  'Phyllis Reynolds Naylor',
  'Piers Anthony',
  'Poul Anderson',
  'R. A. Salvatore',
  'R. L. Stine',
  'R.L. Stine',
  'Rachel Lee',
  'Rainer Maria Rilke',
  'Ray Bradbury',
  'Readers Digest',
  'Rebecca Brandewyne',
  'Rebecca Winters',
  'Rebecca York',
  'Reginald Hill',
  'Rex Stout',
  'Richard Laymon',
  'Richard Scarry',
  'Rita Mae Brown',
  'Roald Dahl',
  'Robert A. Heinlein',
  'Robert B. Parker',
  'Robert Barnard',
  'Robert Jordan',
  'Robert Louis Stevenson',
  'Robert Ludlum',
  'Robert Rankin',
  'Robert Silverberg',
  'Robin Cook',
  'Robin Jones Gunn',
  'Robyn Donald',
  'Roger Hargreaves',
  'Roger Zelazny',
  'Rosamunde Pilcher',
  'Rudyard Kipling',
  'Rumiko Takahashi',
  'Ruth Langan',
  'Ruth Rendell',
  'Sally Wentworth',
  'Sandra Brown',
  'Sandra Field',
  'Sandra Marton',
  'Sara Craven',
  'Sara Orwig',
  'Sara Wood',
  'Scholastic Books',
  'Scott Adams',
  'Sharon Sala',
  'Sherryl Woods',
  'Sidney Sheldon',
  'Simon Brett',
  'Simon Hawke',
  'Simone De Beauvoir',
  'Spike Milligan',
  'Stan Berenstain',
  'Stanislaw Lem',
  'Stella Cameron',
  'Stephen Cosgrove',
  'Stephen King',
  'Stephen R. Donaldson',
  'Steve Jackson',
  'Steve Perry',
  'Stuart M. Kaminsky',
  'Stuart Woods',
  'Sue Grafton',
  'Sunset Books',
  'Susan Johnson',
  'Susan Mallery',
  'Susan Saunders',
  'Susan Wiggs',
  'Suzanne Brockmann',
  'Suzanne Weyn',
  'Tabor Evans',
  'Tamora Pierce',
  'Tanith Lee',
  'Terry Brooks',
  'Terry Pratchett',
  'Thomas Mann',
  'Thomas Merton',
  'Tim Lahaye',
  'Time Life Books',
  'Time-Life Books',
  'Tisha Hamilton',
  'Todd Strasser',
  'Tom Clancy',
  'Tom Sharpe',
  'Tom Smith',
  'Tony Abbott',
  'Tracey West',
  'Umberto Eco',
  'Unknown',
  'Ursula K. Le Guin',
  'V. C. Andrews',
  'V.C. Andrews',
  'Valerie Tripp',
  'Vicki Lewis Thompson',
  'Victoria Holt',
  'Victoria Pade',
  'Virginia Woolf',
  'W. E. B. Griffin',
  'Walt Disney',
  'Walt Disney Productions',
  'Walter Dean Myers',
  'Walter Mosley',
  'Warren Murphy',
  'William Shakespeare',
  'William Shatner',
  'William W. Johnstone',
  'Wolfgang Hohlbein',
  'Zane Grey',
]
