export const publishers = [
  '1Stbooks Library',
  'Ace Books',
  'Actes Sud',
  'Adams Media Corporation',
  'Addison Wesley Publishing Company',
  'Addison-Wesley',
  'Addison-Wesley Pub Co',
  'Aladdin',
  'Albert Whitman  Company',
  'Albin Michel',
  'Alfred A. Knopf',
  'Algonquin Books Of Chapel Hill',
  'Alianza',
  'Alpha Books',
  'Alyson Publications',
  'Anagrama',
  'Anchor',
  'Anchor Books/Doubleday',
  'Andrews Mcmeel Pub',
  'Andrews Mcmeel Publishing',
  'Apple',
  'Arcade Publishing',
  'Arrow (A Division Of Random House Group)',
  'Aspect',
  'Atheneum',
  'Atlantic Monthly Press',
  'Atria',
  'Atria Books',
  'Audio Literature',
  'Aufbau Tb',
  'Augsburg Fortress Publishers',
  'Authorhouse',
  'Avery Publishing Group',
  'Avon',
  'Avon Books',
  'Back Bay Books',
  'Baen',
  'Baker Book House',
  'Baker Pub Group',
  'Ballantine Books',
  'Bantam',
  'Bantam Books',
  'Bantam Books (Mm)',
  'Bantam Dell Pub Group',
  'Bantam Doubleday Dell',
  'Barbour Publishing',
  'Barnes Noble Books',
  'Barrons Educational Series',
  'Barrons Educational Series Inc',
  'Basic Books',
  'Beacon Press',
  'Beltz',
  'Berkley Pub Group',
  'Berkley Pub Group (Mm)',
  'Berkley Publishing Group',
  'Bertelsmann, Mnchen',
  'Bethany House Publishers',
  'Blackwell Publishers',
  'Bloomsbury Publishing Plc',
  'Book Sales',
  'Bookthrift Co',
  'Broadman  Holman Publishers',
  'Broadway',
  'Broadway Books',
  'Btb',
  'Btb Bei Goldmann',
  'Cambridge University Press',
  'Candlewick Press (Ma)',
  'Carol Publishing Corporation',
  'Carroll  Graf Publishers',
  'Cartwheel Books',
  'Celestial Arts',
  'Chronicle Books',
  'Chronicle Books Llc',
  'Citadel Press',
  'Clarion Books',
  'Clarkson N Potter Publishers',
  'Cliffs Notes',
  'Collins',
  'Columbia University Press',
  'Conari Press',
  'Concordia Publishing House',
  'Consortium Book Sales  Dist',
  'Cook Communications Ministries Intl',
  'Counterpoint Press',
  'Course Technology',
  'Crescent',
  'Crown Publishers',
  'Crown Publishing Group (Ny)',
  'Da Capo Press',
  'Dark Horse Comics',
  'David R. Godine Publisher',
  'Daw Books',
  'Dc Comics',
  'Del Rey',
  'Del Rey Books',
  'Delacorte Press',
  'Dell',
  'Dell Publishing',
  'Dell Publishing Company',
  'Delta',
  'Denol',
  'Dial Books',
  'Diamond/Charter',
  'Diogenes',
  'Diogenes Verlag',
  'Disney Press',
  'Distribooks',
  'Distribooks Inc',
  'Dk Publishing Inc',
  'Dorling Kindersley',
  'Dorling Kindersley Publishing',
  'Doubleday',
  'Doubleday Books',
  'Dover Publications',
  'Dover Pubns',
  'Droemer Knaur',
  'Droemersche Verlagsanstalt Th. Knaur Nachf., Gmbh  Co.',
  'Dtv',
  'Dutton Books',
  'E.D.C. Publishing',
  'Ecco',
  'Ediciones B',
  'Editions 10/18',
  'Editions 84',
  'Egmont Childrens Books',
  'Einaudi',
  'Eos',
  'F  W Pubns',
  'Faber  Faber',
  'Faber And Faber Ltd',
  'Facts On File',
  'Farrar Straus  Giroux',
  'Farrar Straus Giroux',
  'Farrar, Straus And Giroux',
  'Farrar, Straus And Giroux (Byr)',
  'Fawcett',
  'Fawcett Books',
  'Feltrinelli',
  'Firefly Books Ltd',
  'Fireside',
  'Fischer (Tb.), Frankfurt',
  'Five Star (Me)',
  'Flammarion',
  'Fodors Travel Publications',
  'For Dummies',
  'Forge',
  'Forge Books',
  'Free Press',
  'Gallimard',
  'Globe Pequot',
  'Globe Pequot Pr',
  'Gold Eagle',
  'Golden Books',
  'Goldencraft',
  'Goldmann',
  'Gramercy',
  'Gramercy Books',
  'Grosset  Dunlap',
  'Grove Press',
  'Harcourt',
  'Harcourt Childrens Books',
  'Harlequin',
  'Harlequin Books',
  'Harlequin Mills  Boon Ltd',
  'Harper  Row',
  'Harper Mass Market Paperbacks',
  'Harper Mass Market Paperbacks (Mm)',
  'Harperaudio',
  'Harperbusiness',
  'Harpercollins',
  'Harpercollins Childrens Books',
  'Harpercollins Juvenile Books',
  'Harpercollins Publishers',
  'Harperentertainment',
  'Harperfestival',
  'Harperresource',
  'Harpersanfrancisco',
  'Harpertorch',
  'Harpertrophy',
  'Harry N Abrams',
  'Harry N Abrams Inc',
  'Harvard University Press',
  'Harvest Books',
  'Harvest House Pub',
  'Harvest House Publishers',
  'Hay House',
  'Hazelden Publishing  Educational Services',
  'Headline',
  'Health Communications',
  'Heinemann',
  'Henry Holt  Co',
  'Henry Holt  Company',
  'Heyne',
  'Hodder  Stoughton General Division',
  'Holiday House',
  'Houghton Mifflin',
  'Houghton Mifflin Co',
  'Houghton Mifflin Company',
  'House Of Stratus',
  'Hyperion',
  'Hyperion Books',
  'Hyperion Books For Children',
  'I Books',
  'Independent Pub Group',
  'Indiana University Press',
  'Intervarsity Press',
  'Intl Specialized Book Service Inc',
  'Iuniverse',
  'Ivy Books',
  'Jai Lu',
  'Jeremy P. Tarcher',
  'John Wiley  Sons',
  'John Wiley  Sons Inc',
  'Johns Hopkins University Press',
  'Jossey-Bass',
  'Jove Books',
  'Judy Piatkus Publishers Ltd',
  'Kensington Pub Corp (Mm)',
  'Kensington Publishing Corporation',
  'Kiepenheuer  Witsch',
  'Knopf',
  'Kodansha America',
  'Landoll',
  'Laure Leaf',
  'Laurel Leaf',
  'Laurel-Leaf Books',
  'Lbbe',
  'Le Livre De Poche',
  'Lectorum Pubns (J)',
  'Leisure Arts',
  'Leisure Books',
  'Lgf',
  'Little Apple',
  'Little Brown  Co',
  'Little Brown And Company',
  'Little Simon',
  'Little, Brown',
  'Livre De Poche',
  'Llewellyn Publications',
  'Llewellyn Pubns',
  'Lonely Planet',
  'Lonely Planet Publications',
  'Love Spell',
  'Loveswept',
  'Macmillan',
  'Macmillan Computer Pub',
  'Macmillan General Reference',
  'Macmillan Publishing Company.',
  'Main Street Books',
  'Mandarin',
  'Mariner Books',
  'Mcclelland  Stewart',
  'Mcgraw-Hill',
  'Mcgraw-Hill Companies',
  'Mcgraw-Hill Humanities/Social Sciences/Languages',
  'Mcgraw-Hill Osborne Media',
  'Mcgraw-Hill Trade',
  'Mcgraw-Hill/Contemporary Books',
  'Meredith Books',
  'Methuen Publishing Ltd',
  'Microsoft Press',
  'Mira',
  'Mira Books',
  'Miramax',
  'Mjf Books',
  'Modern Library',
  'Moody Pr',
  'Moody Publishers',
  'Multnomah',
  'Mysterious Press',
  'National Geographic',
  'Natl Book Network',
  'Nelson Books',
  'New Amer Library',
  'New Amer Library (Mm)',
  'New American Library',
  'New Directions Publishing Corporation',
  'Not Avail',
  'Ntc/Contemporary Publishing Company',
  'Onyx Books',
  'Orb Books',
  'Oreilly',
  'Orion',
  'Orion Publishing Co',
  'Overlook Press',
  'Owl Books (Ny)',
  'Oxford Univ Pr',
  'Oxford University Press',
  'Oxmoor House',
  'Pages Publishing Group',
  'Palgrave Macmillan',
  'Pan Books Ltd',
  'Pan Macmillan',
  'Pantheon Books',
  'Paulist Press',
  'Pearson Education',
  'Penguin',
  'Penguin Books',
  'Penguin Books Ltd',
  'Penguin Putnam',
  'Penguin Putnammass',
  'Penguin Putnamtrade',
  'Penguin Uk',
  'Penguin Usa',
  'Perennial',
  'Perennial Currents',
  'Perigee Books',
  'Perseus Books Group',
  'Perseus Publishing',
  'Philipp Reclam, Jun Verlag Gmbh',
  'Picador',
  'Picador Usa',
  'Pinnacle Books',
  'Pinnacle Books (Mm)',
  'Piper',
  'Planeta',
  'Planeta Pub Corp',
  'Plaza  Janes Editores, S.A.',
  'Pleasant Company Publications',
  'Plume Books',
  'Pocket',
  'Pocket Books',
  'Pocket Star',
  'Poisoned Pen Press',
  'Prentice Hall',
  'Prentice Hall Art',
  'Prentice Hall Ptr',
  'Prentice-Hall',
  'Price Stern Sloan',
  'Price Stern Sloan Pub (J)',
  'Prima Lifestyles',
  'Prime Crime',
  'Princeton University Press',
  'Prometheus Books',
  'Pub Group West',
  'Publicaffairs',
  'Publications International',
  'Publishamerica',
  'Puffin Books',
  'Putnam Pub Group',
  'Putnam Publishing Group',
  'Que',
  'Quill',
  'Random House',
  'Random House Books For Young Readers',
  'Random House Childrens Books',
  'Random House Childrens Pub',
  'Random House Inc',
  'Random House Trade',
  'Random House Trade Paperbacks',
  'Random House Value Pub',
  'Random House Value Publishing',
  'Readers Digest',
  'Readers Digest Association',
  'Regan Books',
  'Regnery Publishing',
  'Revell',
  'Riverhead Books',
  'Roc',
  'Rodale Books',
  'Rodale Press',
  'Rough Guides Limited',
  'Routledge',
  'Rowohlt Tb.',
  'Running Press Book Publishers',
  'Rutledge Hill Press',
  'Sagebrush Bound',
  'Sams',
  'Scherz',
  'Scholastic',
  'Scholastic Inc',
  'Scholastic Library Pub',
  'Scholastic Paperbacks',
  'Scholastic Paperbacks (Mm)',
  'Scholastic Paperbacks (T)',
  'Scribner',
  'Scribner Paper Fiction',
  'Seal Press (Wa)',
  'Serpents Tail',
  'Seuil',
  'Shambhala',
  'Signet Book',
  'Signet Classics',
  'Silhouette',
  'Silhouette Books',
  'Simon  Schuster',
  'Simon  Schuster (Trade Division)',
  'Simon  Schuster Audio',
  'Simon  Schuster Childrens Publishing',
  'Simon  Schuster Merchandise ',
  'Simon Pulse',
  'Simon Spotlight',
  'Simon Spotlight Entertainment',
  'Simon Spotlight/Nickelodeon',
  'Skylark',
  'Skylark Books',
  'Smithmark Pub',
  'Smithmark Publishers',
  'Soho Press',
  'Sourcebooks',
  'Spectra Books',
  'St Martins Pr',
  'St Martins Pr (Mm)',
  'St. Martins Griffin',
  'St. Martins Minotaur',
  'St. Martins Paperbacks',
  'St. Martins Press',
  'Star Trek',
  'Starfire',
  'Steeple Hill',
  'Sterling Pub Co Inc',
  'Sterling Publishing',
  'Stoddart',
  'Storey Books',
  'Suhrkamp',
  'Sweet Valley',
  'Sybex Inc',
  'Ten Speed Pr',
  'Ten Speed Press',
  'Tfh Publications',
  'Thames  Hudson',
  'The Lyons Press',
  'Thomas Dunne Books',
  'Thomas Nelson',
  'Thomas Nelson Inc',
  'Thomson Learning',
  'Thorndike Pr',
  'Thorndike Press',
  'Thorsons Publishers',
  'Three Rivers Press',
  'Three Rivers Press (Ca)',
  'Time Warner Books Uk',
  'Time-Life Books',
  'Times Books',
  'Tokyopop',
  'Topaz',
  'Tor Books',
  'Tor Books (Mm)',
  'Tor Fantasy',
  'Tor Science Fiction',
  'Touchstone',
  'Trafalgar Square',
  'Trafalgar Square Publishing',
  'Transworld Publishers Ltd',
  'Troll Communications',
  'Troll Communications Llc',
  'Tsr',
  'Tusquets',
  'Tuttle Publishing',
  'Tyndale House Pub',
  'Tyndale House Publishers',
  'Ullstein Buchverlage Gmbh  Co. Kg / Ullstein Tas',
  'Ullstein Tb',
  'Ulverscroft Large Print',
  'University Of California Press',
  'University Of Chicago Press',
  'University Of Nebraska Press',
  'Viking',
  'Viking Books',
  'Viking Press',
  'Villard Books',
  'Vintage',
  'Vintage Books',
  'Vintage Books Usa',
  'Virgin Books',
  'Viz Communications',
  'Viz Llc',
  'W Publishing Group',
  'W W Norton  Co Inc',
  'W. W. Norton  Company',
  'W.W. Norton  Company',
  'Wadsworth Publishing',
  'Walker  Company',
  'Walker Books',
  'Warner Books',
  'Warner Books (Mm)',
  'Warner Books Inc',
  'Washington Square Press',
  'Waterbrook Press',
  'Watson-Guptill Publications',
  'Weiser Books',
  'Westbow Press',
  'Western Pub. Co',
  'White Wolf Pub',
  'Wiley',
  'William Morrow',
  'William Morrow  Company',
  'Wizards Of The Coast',
  'Workman Publishing',
  'Worldwide Library',
  'Writers Club Press',
  'Writers Digest Books',
  'Xlibris Corporation',
  'Yale University Press',
  'Yearling',
  'Yearling Books',
  'Zebra Books',
  'Zondervan',
  'Zondervan Publishing Company',
]
